### ISSUE TITLE
Preview other Bench Pokemon is gone

### ISSUE THREAD

**Issue by Pablotir** [coltonb/pokemon-showdown-type-helper#8]
When I try to look at the other mons on my bench the usual popup with moveset and typing is missing completely. I tested with the extension missing in incognito and in a different browser and the game does its usual pop up preview.

**Comment by coltonb** [comment]
Thanks for the heads up. I recently rewrote the app so it could do more elaborate tweaks, so I'm not super surprised I broke something. I will patch today hopefully 👍

**Comment by coltonb** [comment]
Fixed in v0.0.7

**Comment by Pablotir** [comment]
Thank you! I'll test it out later.

**Comment by coltonb** [comment]
> Thank you! I'll test it out later.

The chrome web store has a 12-24 submission approval process so it might not be until tomorrow that it's live. Keep me posted!

**Comment by Pablotir** [comment]
Firefox updated the extension and works! I don't see any bugs for now. I'll test on chrome tomorrow.
